apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gmcert-editor
rules:
  - apiGroups: ["networking.gke.io"]
    resources: ["managedcertificates"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beconf-editor
rules:
  - apiGroups: ["cloud.google.com"]
    resources: ["backendconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-deployer-beconfig-editor-ANY_NAMESPACE
  namespace: ###### ANY_NAMESPACE ######
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beconf-editor
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-deployer-gmcert-editor-ANY_NAMESPACE
  namespace: ###### ANY_NAMESPACE ######
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gmcert-editor
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-deployer-ANY_NAMESPACE
  namespace: ###### ANY_NAMESPACE ######
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: default